# Generated by Django 4.2.13 on 2024-07-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(related_name='products', to='products.ingredient'),
        ),
    ]
